trigger:
  branches:
    include:
    - main

variables:
  ServiceConnectionName: 'YourServiceConnectionName'
  bk-rg-name: 'terraform-rg'
  bk-str-account-name: 'tfstate'
  bk-container-name: 'tfcontainer'

pool:
  vmImage: ubuntu-latest

stages:
- stage: plan_dev
  jobs:
  - template: azure-pipeline-jobs/plan.yml@pipelineJobs
    parameters:
      env: dev

- stage: deploy_dev
  dependsOn: plan_dev
  condition: succeeded('plan_dev')
  jobs:
  - template: azure-pipeline-jobs/deploy.yml@pipelineJobs
    parameters:
      env: dev

- stage: plan_uat
  jobs:
  - template: azure-pipeline-jobs/plan.yml@pipelineJobs
    parameters:
      env: uat

- stage: deploy_uat
  dependsOn: plan_uat
  condition: succeeded('plan_uat')
  jobs:
  - template: azure-pipeline-jobs/deploy.yml@pipelineJobs
    parameters:
      env: uat

- stage: plan_prod
  jobs:
  - template: azure-pipeline-jobs/plan.yml@pipelineJobs
    parameters:
      env: prod

- stage: deploy_prod
  dependsOn: plan_prod
  condition: succeeded('plan_prod')
  jobs:
  - template: azure-pipeline-jobs/deploy.yml@pipelineJobs
    parameters:
      env: prod

- stage: destroy
  condition: always()
  jobs:
  - template: azure-pipeline-jobs/destroy.yml@pipelineJobs
    parameters:
      env: dev
