trigger:
  branches:
    include:
    - main

resources:
  repositories:
    - repository: azure_jobs
      type: git
      name: aditya504/web-app-code
      ref: refs/heads/main
      endpoint: github-access

variables:
  ServiceConnectionName: 'Azure-Subscription-1'
  bk-rg-name: 'testing-terraform-code'
  bk-str-account-name: 'testsa504504'
  bk-container-name: 'tfcontainer'

pool:
  vmImage: ubuntu-latest

stages:
- stage: plan_dev
  jobs:
  - template: plan.yml@azure_jobs	
    parameters:
      env: dev

- stage: deploy_dev
  dependsOn: plan_dev
  condition: succeeded('plan_dev')
  jobs:
  - template: deploy.yml@azure_jobs
    parameters:
      env: dev

- stage: plan_uat
  jobs:
  - template: plan.yml@azure_jobs
    parameters:
      env: uat

- stage: deploy_uat
  dependsOn: plan_uat
  condition: succeeded('plan_uat')
  jobs:
  - template: deploy.yml@azure_jobs
    parameters:
      env: uat

- stage: plan_prod
  jobs:
  - template: plan.yml@azure_jobs
    parameters:
      env: prod

- stage: deploy_prod
  dependsOn: plan_prod
  condition: succeeded('plan_prod')
  jobs:
  - template: deploy.yml@azure_jobs
    parameters:
      env: prod

- stage: destroy
  condition: always()
  jobs:
  - template: destroy.yml@azure_jobs
    parameters:
      env: dev
